"""Helpers for exporting model-fit statistics as LaTeX macros.

The model-fitting notebooks accumulate macros in a dict and write them with
write_macros(). The manuscript inputs the resulting .tex files so that no
computed value is hardcoded in the text. Macro names may contain only letters
(LaTeX command names cannot contain digits), so experiments are spelled out
(e.g., expTwoSocialWr, not exp2SocialWr).
"""

import re

_NAME_RE = re.compile(r"^[A-Za-z]+$")


def fmt_num(x, digits=2):
    """Format a number with a fixed number of decimal places."""
    return f"{x:.{digits}f}"


def fmt_int(x):
    """Format an integer (e.g., counts, degrees of freedom)."""
    return str(round(x))


def fmt_p(p, digits=3):
    """Format a p-value with its comparator, for use as "$p \\macroName$".

    Produces "= 0.014" style values, or "< 0.001" below the cutoff.
    """
    cutoff = 10**-digits
    if p < cutoff:
        return f"< {fmt_num(cutoff, digits)}"
    return f"= {fmt_num(p, digits)}"


def write_macros(macros, path):
    """Write a dict of macro values to a .tex file of \\newcommand definitions."""
    bad = [name for name in macros if not _NAME_RE.match(name)]
    if bad:
        raise ValueError(f"Macro names must contain only letters: {bad}")
    lines = [
        "% Auto-generated by the analysis pipeline -- do not edit by hand.",
        "% Source: model/",
    ]
    lines += [f"\\newcommand{{\\{name}}}{{{value}}}" for name, value in macros.items()]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path
