---
title: "transparency pilot / stimulus norming study"
author: "Alicia Chen"
date: "2024-12-18"
output:
  html_document: default
---

```{r setup, include=FALSE}
library(here)
library(tidyverse)
library(tidyboot)
library(glue)
library(lme4)
library(lmerTest)
library(emmeans)
library(simr)

theme_set(theme_classic(base_size = 20))
options(contrasts = c(unordered = "contr.sum", ordered = "contr.poly"))
```

```{r}
data <- read_csv(here("data/transparency/selection_trials.csv")) %>% 
  mutate(correct = ifelse(correct == TRUE, 1, 0)) %>% 
  filter(understood == "yes")
```
How many participants? M(SD) age? 

```{r}
nrow(data %>% distinct(subject_id))
```


How much of each utterance? There should be ~40

```{r}
means.by.label = data %>% 
  group_by(tangram_set, target, earlier, length, label) %>% 
  tidyboot_mean(correct, na.rm = T)

means.by.label
# save to csv
write_csv(means.by.label, here("data/transparency/means_by_label.csv"))
```

Aggregate and compare informativity of earlier vs. later utterances

```{r}
earlier.later.all.means <- data %>% 
  group_by(earlier) %>% 
  tidyboot_mean(correct, na.rm = T)
```

```{r fig.width=4, fig.height=4}
ggplot(earlier.later.all.means, aes(x = earlier, y = empirical_stat)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), size = 2, width = 0.0) +
  geom_hline(yintercept = 1/6, color = "red", linetype = "dashed") +
  labs(x = "Earlier vs. later utterance", y = "Proportion correct") +
  ylim(0, 1)
```

Correlate utterance length with response

```{r}
ggplot(data, aes(x = length, y = correct)) +
  geom_jitter(height = 0.2, alpha = 0.05, stroke = 0, size = 2.5) +
  geom_smooth(method = "gam") +
  scale_y_continuous(breaks = c(0, 1), labels = c("incorrect", "correct")) +
  labs(x = "utterance length", y = "correct")
```
How much variability is there between labels? 

```{r}
truncate_label <- function(text, max_words = 6) {
  words <- unlist(strsplit(text, "\\s+")) # Split text into words
  if (length(words) > max_words) {
    paste(paste(words[1:max_words], collapse = " "), "...", sep = "")
  } else {
    text
  }
}

means.by.label$short_label <- sapply(means.by.label$label, truncate_label)

for (set in c(0, 1, 2)) {
  p <- ggplot(means.by.label %>% filter(tangram_set == set), aes(x = reorder(short_label, empirical_stat), y = empirical_stat, color = earlier)) +
    geom_point(size = 3) +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), size = 2, width = 0.0) +
    geom_text(aes(label = target), vjust = 4, show.legend = F) +
    geom_hline(yintercept = 1/6, color = "red", linetype = "dashed") +
    labs(x = "Label", y = "Proportion correct", title = glue("tangram set {set}")) +
    ylim(0, 1) +
    theme(axis.text.x = element_text(size = 9, angle = 40, hjust = 1))
  print(p)
}
```





