# Helpers for exporting statistics as LaTeX macros.
#
# Each analysis document accumulates macros in a named list and writes them to
# a macros.tex file with write_macros(). The manuscript inputs these files so
# that no computed value is ever hardcoded in the text. Macro names may contain
# only letters (LaTeX command names cannot contain digits), so experiments are
# spelled out (e.g., expTwoReferEitherM, not exp2ReferEitherM).

# Format a number with a fixed number of decimal places.
fmt_num <- function(x, digits = 2) {
  formatC(x, format = "f", digits = digits)
}

# Format an integer (e.g., counts, degrees of freedom).
fmt_int <- function(x) {
  formatC(round(x), format = "d")
}

# Format a p-value with its comparator, for use as "$p \macroName$".
# Produces "= 0.014" style values, or "< 0.001" below the cutoff.
fmt_p <- function(p, digits = 3) {
  cutoff <- 10^(-digits)
  if (p < cutoff) {
    paste0("< ", fmt_num(cutoff, digits))
  } else {
    paste0("= ", fmt_num(p, digits))
  }
}

# Format an estimate with its confidence interval, e.g. "1.60\,[1.14, 2.06]".
fmt_est_ci <- function(est, lo, hi, digits = 2) {
  paste0(
    fmt_num(est, digits),
    "\\,[",
    fmt_num(lo, digits),
    ", ",
    fmt_num(hi, digits),
    "]"
  )
}

# Format a percentage, e.g. "98.4\%".
fmt_pct <- function(x, digits = 1, proportion = TRUE) {
  if (proportion) {
    x <- 100 * x
  }
  paste0(fmt_num(x, digits), "\\%")
}

# Extract estimate/z/p macro values from one row of an emmeans summary data
# frame (means or contrasts, on the asymptotic z scale). Returns a list with
# elements M (estimate with CI), Z, and P, to be combined via add_macros().
emm_row_macros <- function(row, est_col = c("emmean", "estimate")) {
  est_col <- intersect(est_col, names(row))[1]
  list(
    M = fmt_est_ci(row[[est_col]], row$asymp.LCL, row$asymp.UCL),
    Z = fmt_num(row$z.ratio),
    P = fmt_p(row$p.value)
  )
}

# Append a list of values to the macro list, prefixing each name,
# e.g. add_macros(macros, "expTwoReferEither", list(M = ..., Z = ...)).
add_macros <- function(macros, prefix, values) {
  names(values) <- paste0(prefix, names(values))
  c(macros, values)
}

# Deparse the random-effects part of a fitted lme4 model, e.g.
# "(condition | subject_id) + (1 | item_id:option2.tangram)". Used to export
# each model's final structure for the manuscript's appendix table, so the
# table always reflects the models actually fit. Note that nested terms like
# (1 | set/tangram) are shown in their expanded form.
re_terms <- function(mod) {
  bars <- lme4::findbars(formula(mod))
  paste0("(", vapply(bars, deparse1, character(1)), ")", collapse = " + ")
}

# Write a named list of macro values to a .tex file of \newcommand definitions.
# Names are validated to be letters-only so the file always compiles.
write_macros <- function(macros, path) {
  bad <- names(macros)[!grepl("^[A-Za-z]+$", names(macros))]
  if (length(bad) > 0) {
    stop("Macro names must contain only letters: ", paste(bad, collapse = ", "))
  }
  lines <- vapply(
    names(macros),
    function(name) {
      sprintf("\\newcommand{\\%s}{%s}", name, as.character(macros[[name]]))
    },
    character(1)
  )
  header <- c(
    "% Auto-generated by the analysis pipeline -- do not edit by hand.",
    sprintf("%% Source: %s", basename(dirname(path)))
  )
  writeLines(c(header, lines), path)
  invisible(path)
}
