"""Generate the manuscript's random-effects structure appendix table.

Reads the per-experiment re_structures.csv files (written by the analysis
Rmds directly from the fitted lme4 objects) and writes a LaTeX tabular to
analysis/re_structure_table.tex, which `make manuscript-stats` copies into
manuscript/stats/ for the appendix to input. Variable names are mapped to the
reader-facing terms used in the paper. Run from the project root:
uv run python analysis/utils/re_structure_table.py
"""

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "analysis" / "re_structure_table.tex"

SOURCES = [
    ("analysis/free-response/re_structures.csv", "1"),
    ("analysis/shared-unique/re_structures.csv", "2"),
    ("analysis/earlier-later/re_structures.csv", "3"),
    ("analysis/varied_audience/re_structures.csv", "4"),
]

# Ordered longest-first so composite names are replaced before their parts.
REPLACEMENTS = [
    ("item_id:option2.tangram", "tangram"),
    ("item_id:option1.tangram", "tangram"),
    ("option2.tangram:item_id", "tangram"),
    ("option1.tangram:item_id", "tangram"),
    ("item_id:tangram", "tangram"),
    ("tangram:item_id", "tangram"),
    ("selected_tangram", "tangram"),
    ("subject_id", "participant"),
    ("item_id", "set"),
    ("prop_naive", "prop.\\ naive"),
    ("prop_outgroup", "prop.\\ out-group"),
    ("shared", "tangram type"),
]


def display(re_formula):
    for old, new in REPLACEMENTS:
        re_formula = re_formula.replace(old, new)
    if "_" in re_formula:
        raise ValueError(f"unmapped variable name in: {re_formula}")
    return re_formula


rows = []
for path, exp in SOURCES:
    with open(ROOT / path) as f:
        for rec in csv.DictReader(f):
            rows.append((exp, rec["model"], display(rec["random_effects"])))

lines = [
    "% Auto-generated by analysis/utils/re_structure_table.py -- do not edit by hand.",
    "\\begin{tabular}{lll}",
    "\\toprule",
    "Exp. & Model & Random effects \\\\",
    "\\midrule",
]
prev_exp = None
for exp, model, re_formula in rows:
    show_exp = exp if exp != prev_exp else ""
    prev_exp = exp
    lines.append(f"{show_exp} & {model} & {re_formula} \\\\")
lines += ["\\bottomrule", "\\end{tabular}"]

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} ({len(rows)} rows)")
