"""Generate the manuscript's sensitivity-analysis appendix table.

Reads the per-experiment sensitivity.csv files (written by the analysis Rmds)
and writes a LaTeX tabular to analysis/sensitivity_table.tex, which `make
manuscript-stats` copies into manuscript/stats/ for the appendix to input.
Run from the project root: uv run python analysis/utils/sensitivity_table.py
"""

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "analysis" / "sensitivity_table.tex"

# (csv path, experiment label, effect label, filter on the `model` column)
SOURCES = [
    (
        "analysis/free-response/sensitivity.csv",
        "1",
        "Social goal (tangram choice)",
        "tangram_choice",
    ),
    (
        "analysis/free-response/sensitivity.csv",
        "1",
        "Social goal (utterance length)",
        "utt_length",
    ),
    (
        "analysis/free-response/sensitivity.csv",
        "1",
        "Social goal (semantic distance)",
        "semantic_distance",
    ),
    (
        "analysis/shared-unique/sensitivity.csv",
        "2",
        "Refer-known $-$ social-known",
        None,
    ),
    (
        "analysis/earlier-later/sensitivity.csv",
        "3",
        "Refer-known $-$ social-known",
        None,
    ),
    ("analysis/varied_audience/sensitivity.csv", "4", "Social goal", None),
]


def fmt_p(p, digits=3):
    p = float(p)
    cutoff = 10**-digits
    return f"$<{cutoff:.3f}$" if p < cutoff else f"${p:.3f}$"


def fmt_spec(spec, singular):
    label = (
        spec.replace("final (reported)", "final (reported)")
        .replace("maximal (singular)", "maximal")
        .replace("previous (singular)", "previous")
    )
    note = "\\textsuperscript{s}" if singular.upper() == "TRUE" else ""
    return label + note


rows = []
for path, exp, effect, model_filter in SOURCES:
    with open(ROOT / path) as f:
        for rec in csv.DictReader(f):
            if model_filter is not None and rec.get("model") != model_filter:
                continue
            stat = rec.get("z") or rec.get("stat")
            rows.append(
                (
                    exp,
                    effect,
                    fmt_spec(rec["specification"], rec["singular"]),
                    f"{float(rec['estimate']):.2f} ({float(rec['SE']):.2f})",
                    f"{float(stat):.2f}",
                    fmt_p(rec["p"]),
                )
            )

lines = [
    "% Auto-generated by analysis/utils/sensitivity_table.py -- do not edit by hand.",
    "\\begin{tabular}{llllrl}",
    "\\toprule",
    "Exp. & Effect & Random-effects specification & Est. (SE) & $z$/$t$ & $p$ \\\\",
    "\\midrule",
]
prev = None
for exp, effect, spec, est, stat, p in rows:
    show_exp = exp if (exp, effect) != prev else ""
    show_eff = effect if (exp, effect) != prev else ""
    prev = (exp, effect)
    lines.append(f"{show_exp} & {show_eff} & {spec} & {est} & {stat} & {p} \\\\")
lines += ["\\bottomrule", "\\end{tabular}"]

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} ({len(rows)} rows)")
